language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # SFML
  - sudo apt-get install libsfml-dev
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Other prerequisites
  - ./download_other_githubs

services:
  - xvfb

script: 
  # Console test
  - qmake -qt=qt5 SearchAndDestroyChessConsoleTest.pro
  - make debug
  - ./SearchAndDestroyChessConsoleTest
  # Desktop
  - qmake -qt=qt5 SearchAndDestroyChess.pro
  - make debug
  - ./SearchAndDestroyChess &
  - sleep 10
  - sudo killall SearchAndDestroyChess
  # OCLint
  - ./do_oclint
  # Get code coverage
  - ./get_code_cov > /dev/null
  - codecov > /dev/null
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
